services:
  builder:
    image: rgb-lib-kotlin
    build: .
    environment:
      MYUID: 1000
      MYGID: 1000
    volumes:
      - ./:/home/rgb-lib-kotlin/rgb-lib-kotlin/
      - ./cargo_cache:/usr/local/cargo/registry/
      - ./gradle_cache:/home/rgb-lib-kotlin/.gradle/
